name: JitDocker Builder

on:
  workflow_dispatch:
    inputs:
      githubRepo:
        description: "Github Repository to build (owner/name)"
        type: text
        required: true
      branch:
        description: "Git Branch to build"
        type: text
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Parse Git URL
        id: gitParse
        uses: theowenyoung/git-url-parse@v1
        with:
          url: https://github.com/${{ inputs.githubRepo }}
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          repository: ${{ inputs.githubRepo }}
          ref: ${{ inputs.branch }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: jitdockerio/${{ steps.gitParse.outputs.owner }}.${{ steps.gitParse.outputs.name }}:${{ inputs.branch }}
