name: JitDocker Builder

on:
  workflow_dispatch:
    inputs:
      githubRepo:
        description: "Github Repository to build (owner/name)"
        type: string
        required: true
      branch:
        description: "Git Branch to build"
        type: string
        required: false
      id:
        description: "Run identifier (for status checks)"
        required: false

jobs:
  id:
    name: Workflow ID Provider
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.event.inputs.id }}
        run: echo run identifier ${{ inputs.id }}
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Parse Git URL
        id: gitParse
        uses: theowenyoung/git-url-parse@v1
        with:
          url: https://github.com/${{ inputs.githubRepo }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "https://github.com/${{ inputs.githubRepo }}.git#refs/heads/${{ inputs.branch }}"
          push: true
          tags: jitdockerio/${{ steps.gitParse.outputs.owner }}.${{ steps.gitParse.outputs.name }}:${{ inputs.branch }}
